server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ 
    registerWithEureka: true
    fetchRegistry: false 
spring:
    application:
        name: testservice 
    datasource: 
        url: jdbc:mysql://localhost/tmall
        username: root
        password: ps123456
        driver-class-name: com.mysql.jdbc.Driver  